apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vtln
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vtln
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vtln
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vtln
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vtln
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hqrh-tenant/rhtap-demo-app/hacbs-test-project-vtln@sha256:5630f2deb9ecaf7d07a9b7670a0eb81a0d42f6c3320633e50de2c1ec80502242
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
