apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vtln
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hqrh-tenant/rhtap-demo-app/hacbs-test-project-vtln@sha256:d3b14dfefcb36cb0105354d72f948fcdc7757a88c05ff6dcb8c5d388b03c3d58
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
